import Link from "next/link";

type Project = {
  slug: string;
  title: string;
  category: string;
  year: string;
  video?: string;
  image?: string;
  tag?: { label: string; bg: string };
  description?: string;
  github?: string;
  site?: string;
};

const projects: Project[] = [
  {
    slug: "project-one",
    title: "Terminal Portfolio",
    category: "Product",
    year: "2025",
    video: "/tui.mp4",
    tag: { label: "Hobby", bg: "bg-red-500" },
    description:
      "Built an SSH-accessible portfolio in Go that renders a fully interactive TUI (Bubble Tea + Lip Gloss) on connect, including a braille-dithered animated ASCII portrait converted from video frames and a Wish-based SSH server deployable as a single binary on Fly.io.",
    github: "https://github.com/sforslime/terminal-site",
  },
  {
    slug: "project-two",
    title: "LetuSell",
    category: "Product",
    year: "2025",
    image: "/letusell.png",
    tag: { label: "In Development", bg: "bg-amber-500" },
    description:
      "An AI campus shopping concierge: university students ask for anything in English or Nigerian Pidgin, get matched to a campus vendor, and are handed straight to that vendor's WhatsApp chat to buy. A grounded LLM pipeline extracts intent as JSON, retrieves matching vendors from the database, and writes replies only from those rows, so it can't invent vendors. Hardened against prompt injection, with vendor phone numbers kept hidden from the model and the API, an admin funnel dashboard for every query, and a Paystack marketplace with automatic split-payment vendor payouts. Built with Next.js, TypeScript, Supabase, and Groq.",
    site: "https://letusell.ng",
  },
  {
    slug: "news-router",
    title: "Nigerian News Router",
    category: "Product",
    year: "2026",
    image: "/news-router.png",
    description:
      "A read-only API across 10 Nigerian newsrooms (WordPress REST and RSS), normalizing every source into a single schema. Daily scheduled ingestion has indexed 9,000+ articles, with publisher licensing enforced per record and every correction tracked as a named-field revision. Groups the same story across outlets into 450+ clusters with neutral per-story summaries generated by Groq from licensed fields only. Built with Python, FastAPI, PostgreSQL (Neon), and Vercel.",
    site: "https://news-router.vercel.app",
    github: "https://github.com/sforslime/news-router",
  },
  {
    slug: "quant-bench",
    title: "Quant-Bench",
    category: "Research",
    year: "2026",
    description:
      "A multilingual LLM quantization study in English, Pidgin, and Yoruba. Benchmarked 2 local LLMs across 5 quantization levels on an Apple M4 for speed, memory, and accuracy, using paired McNemar tests, Holm correction, and bootstrap confidence intervals. A pre-registered test on 573 held-out question pairs showed Yoruba lost ~40% of its reading skill at 3-bit vs. 2–14% for English, while Q4_K_M ran 45–56% faster with 31–34% less GPU memory and no significant English/Pidgin quality loss. Built with Python, NumPy, llama.cpp, and Hugging Face.",
    github: "https://github.com/sforslime/quant-bench",
  },
];

export default function Work() {
  return (
    <section className="px-8 md:px-12 pt-8 pb-24">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-14">
        {projects.map((p) => (
          <div key={p.slug} className="group block">
            <Link
              href={p.site ?? `/work/${p.slug}`}
              {...(p.site && { target: "_blank", rel: "noopener noreferrer" })}
              className="block"
            >
              {p.video ? (
                <video
                  src={p.video}
                  autoPlay
                  loop
                  muted
                  playsInline
                  className="w-full h-auto rounded-sm"
                />
              ) : p.image ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={p.image}
                  alt={p.title}
                  className="w-full h-auto rounded-sm"
                />
              ) : (
                <div className="aspect-[4/3] w-full bg-neutral-100 rounded-sm overflow-hidden flex items-center justify-center text-ink/30 text-sm group-hover:bg-neutral-200 transition">
                  [thumbnail]
                </div>
              )}
              <div className="mt-3 flex items-baseline justify-between text-sm">
                <div className="flex items-baseline gap-2">
                  <span className="font-medium">{p.title}</span>
                  {p.tag && (
                    <span
                      className={`inline-block rounded-full px-2 py-0.5 text-[10px] uppercase tracking-wide text-white ${p.tag.bg}`}
                    >
                      {p.tag.label}
                    </span>
                  )}
                </div>
                <span className="text-ink/60">{p.year}</span>
              </div>
              {p.description && (
                <p className="mt-2 text-sm text-ink/70 leading-relaxed">
                  {p.description}
                </p>
              )}
            </Link>
            {(p.github || p.site) && (
              <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm">
                {p.site && (
                  <a
                    href={p.site}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-ink/70 underline underline-offset-4 hover:text-ink"
                  >
                    Visit site →
                  </a>
                )}
                {p.github && (
                  <a
                    href={p.github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-ink/70 underline underline-offset-4 hover:text-ink"
                  >
                    View on GitHub →
                  </a>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
      <p className="mt-16 text-center text-sm text-ink/50 italic">
        More projects coming soon…
      </p>
    </section>
  );
}
